---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1zlx0rynwmxauhsus44ydex7g39qx3wm02pf3kmvm2c823sumfvms6726f9
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1zlx0rynwmxauhsus44ydex7g39qx3wm02pf3kmvm2c823sumfvms6726f9
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1zlx0rynwmxauhsus44ydex7g39qx3wm02pf3kmvm2c823sumfvms6726f9
