apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:GT+Vbp5ZydoXT5k9yqb37UrY9FNY4DdUplJa3GZuvzp0VVoIcQ==,iv:WkVV6+R1f3shehJTXQdktrmNU4PvRQF7V3QAiDPodvI=,tag:+3fon8aCHtsBJPrevK4g+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlx0rynwmxauhsus44ydex7g39qx3wm02pf3kmvm2c823sumfvms6726f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdUQ0aGxBcmJzY2FzNXB3
            TDBGaENoQXgxYkJ1L2dHUDhqemJIN3F5NEQwCjVzb3ZlUTJ3bkZXcEY0Tkg1Q0tH
            MGswWEVhWFk1VldLQTJxWGhUZUJkdVUKLS0tIFVwOTVtazJ2UnpidThaMlZGaFYx
            UVlobkZ5RVEvQzNkMzNmWVJJbDR4R3cKvvkz7maq0XDWlXYiXYZjKljzooLayD0k
            aK65A8awY8fmcIyLMZIFyIH5ONTAHxyf5dFH/L8pyLn4mmyetsgxPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-04T20:10:21Z"
    mac: ENC[AES256_GCM,data:0c8AiALt3duRZTYBXdXkOai2e5dbcXeWoekSWhVfhsqaWgQ1btG5NX3eitXYeHpnvsTKNj2xBQaT5UP7X5yJUe/+QVyRXKTdv6rO7TLlDeahnYZKHjk8oMPrqr3YBPMCKmtMjqbLMCdmK6xFtPsfR/XG/9vHfho5tacqmUPck08=,iv:9jUZJHaOv0tVzEWTIjXgeZ6w1r7AsMac3euxpyPoPM4=,tag:yB/+Lmpmn17MOThyhIEVVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
