apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:WQD1qD/j/eXmZi9pH0HIEN95IekdSBZO0+gLMlUGiCE0HGJaZQ==,iv:lE3N90vKiSm1oVhIUmrW/22UZVnYQ2foPS2x9qVdoxI=,tag:J761TJDjBjQyRZDta1Px9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlx0rynwmxauhsus44ydex7g39qx3wm02pf3kmvm2c823sumfvms6726f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMlJJTUNydUt6ekUxWkdq
            NEw1VGNhNEVYOTVReXZteTYxTlJuQUNUOUVvCkMwSmFmVTZ2QkI2WWhXVnRaeGFE
            WkZRRHFSYTM0MmxkRUp5RzM5WHRPSEEKLS0tIFFzT3Y0SmViSmZDREVtQitobDRz
            Mms3K1ZGMkQ5NkcydHFOTzlTL0JVU2cKvcLGUCEVqK5DQK0wiPRWdfj8Bm+voddW
            94HTurh/d3npNI/upXBOknhaDkW62SIZrMMoLD5xosrxSCO+MnyHcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-04T15:15:04Z"
    mac: ENC[AES256_GCM,data:1AZisxBAc+r9dMyxPGb3U45o7N2+jP+pPFCxzcYv+eEOP70jZKBO23YO9OLCD/wKUTJ3O8LbjfrMsj/jeN8BE8Mk3RQTsrppmFvaCYBtDx/82esldLF2cyQOIB/L9qg4HaRZ/Ja9yYfksuOFWNSp324HgAx0zimm6wjxGBX4s1Y=,iv:cXMmTnqm6kKXJFOHxT9BKKHKlto10haSq1NJ/IMOylQ=,tag:yS1tSZxCFWNwvDrNLCB3VQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
