apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:pMgBCfNgIx16HdKXo9HQMvBdaD0/Voralq/9,iv:0EZRXOUZni0d8hQLLUnudX4/EePr0732jMh0AUR0FMs=,tag:hFETfabI3Art9e8ppNuaUg==,type:str]
    api-key: ENC[AES256_GCM,data:/6NfzlS43tPUzNfhBS15rq/yjF7PCYO4Ka+uBZvJxLmKctaGUg==,iv:QEYtRlPUSuJFfFSvLZJx3Qaer/UWCbMnM3x8BAt4dF4=,tag:oo6ByuL3D8S1LKYZU4v01g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlx0rynwmxauhsus44ydex7g39qx3wm02pf3kmvm2c823sumfvms6726f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQ3BabVErLzRaKy9MSWFp
            M00rZVpldEU3VkNROEh2V25Zb1MyWWZXaTI0CjRTYmJFOVJTeFdRV25SM0E0QlFy
            UWZGdmVMN0dQUkRFNFMvTmpVZG9YaHcKLS0tIDBLUHdLMEQwODF4aVhwNFp0bjl1
            TlphQU51OTUzd3g1NTNjcFNoWlRPbjAK1Nw9eP4UgJD7OKCmjN8NERsBEkWXsTbY
            Y7ptmCTcmPJGAXvOGEHQ+m91AOL3N1XObK7r8DBnWmIfmOt1HztEeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-04T15:15:04Z"
    mac: ENC[AES256_GCM,data:fo8sYyL70MTW2r5QsBiD6m+Wwns1iBidYv773Kpi4meqmopisjUF9wDiDo7ouTpMRGzjeSJNhn7h2Yv5P3Q8lnvywaJYcCNKk0YXduNirf2bwtFQ8Djl9jywlOtWhVeDI8wblLw9uAQ5oI9USDVCwV/ZJusaRRHp8y8mcehvN/E=,iv:GUVTegqb7KuOorZ0ppp9Ch1KKSFalfXQiESCPn2OK94=,tag:xRL7Oe9myvhhnqpo4ywggQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
