apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:kbpsjfBhcjTDHMkAtbio5xPDXOKVX9hHGFzN,iv:dN+bjFDIj/1tgATnGejebVipRhAfMEMLsK9//I6B1gg=,tag:kcmj1wbAbTYrRH3H3sbGRA==,type:str]
    api-key: ENC[AES256_GCM,data:sOeRsHTuK/vICwIp5fTMjLgFkhzISkucLPg1Y5Tb8wpMK3HkVA==,iv:kIQyogxcdE4YCQGgi8Au/qsRcw93UNFvUEXsUbyvCHg=,tag:IFeKvu4tyWBTPaIJnxX99w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlx0rynwmxauhsus44ydex7g39qx3wm02pf3kmvm2c823sumfvms6726f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS1ZHRGwxWit3VjF3bkRU
            RWdLRFVLNGRGVjBVdHEvR2pTSzExZmRUOTFJCkM1NGlZMm5IT0MzdW5EQkl0dHhp
            Mi9RZEszeDN0S1lzWXJseG1NaTh1TFkKLS0tIFZyRFlneERIUXdYWWV4WG9jNlI5
            UzluWDNzQU9lelE4THdRTG9kWkljbEEKBkl3gUbgPJkjn5gfz4BNSKoSVGYQx26/
            z211mkXkwIWAluaVX54zextiXvLwSB/NwC1n6A01NRyHUiJ1+hyjgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-04T20:10:21Z"
    mac: ENC[AES256_GCM,data:pxH0Ojgf4oak5gU7XfNFuEK1JB1x2s3dnq0LGHMAsKWHchFnpZrVM+evBw0q3uoMu6RNKV7OkC8b9rYWUUFkmfO46UI/4xm3B2dOnm5QIG5A+Dd5i/iDi0m8sWipe7TxJ11t+jItbIeImgZZ0x/q5SAHKiYz45rdpe+inSCFuiQ=,iv:MelsWFgT1Hh/rlRmeLKzJF69E+hYmS4qdZoUtP0XpVM=,tag:ORHZC1hSEFNRAWw1dhcu7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
