apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:l4vkTtjs/CvxHzSukJOeahFSbFVO3QpclmC3ggQ7o6Xy0sUU0LenlIYFofbSxgF52Kvh7aXJmkp4Qb/M,iv:Kh4kX1Nwdgciv0wW8iA5nYdngZzW4rZEVBfEpTwuaAc=,tag:BA5oVFIsQovFDsXSlhMxXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zlx0rynwmxauhsus44ydex7g39qx3wm02pf3kmvm2c823sumfvms6726f9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabG9IVys2S01oZHNVTUw2
            N1N2ZnVhYUh2c3RRa2tUV016TTk4UFhGaGhBCklUM0FxUkVEZy81Y3o1QXFsVUVi
            VFFWQnhOQkZkeTVQWjJjZk5xOFhIME0KLS0tIGt5S1BYclI0STU5R05LM2VOb2p4
            cHFvZUx3LzBUTXVCeWFEeDB1akRJYUkKdeOY7eBfTzPOIY2HwWhFeQ0wjylAUar7
            uNVprKn1vHcxPhWAZgDJOr9+GvlwTRjJRHXAiUvcfkZthjry1Gw4+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-04T15:15:04Z"
    mac: ENC[AES256_GCM,data:96G/n/Dw1vQApL0q1u1CqL4ySN1lNA3P+hUtc1hFxEWgk1KgSBT/yD3pLakVGGr2WSYJRH4ITgWn8vKbubizHF1nDmycQ3CGztaH2GrQjiwQXE7mWM2a2U/p2KUI/GSezso115x0QQvGiiCGHlPE654Wo+0NokOOCZjIywz/5sc=,iv:VMI3i7qGU3u0aDJucgw2ACOYFvRYcyLjKSzV393AL+I=,tag:c+YSlx2bbC17gcgyJBmp2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
