---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  KUBE_VIP_ADDR: "192.168.200.19"
  METALLB_LB_RANGE: "192.168.200.20-192.168.200.50"
  METALLB_K8S_GATEWAY_ADDR: "192.168.200.50"
  METALLB_INGRESS_ADDR: "192.168.200.49"
